### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by zidingz** [jspark311/BuriedUnderTheNoiseFloor#2]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jspark311** [comment]
Done.
https://github.com/jspark311/BuriedUnderTheNoiseFloor/blob/master/SECURITY.md

I'm curious to hear what you found.

**Comment by JamieSlome** [comment]
@jspark311 - great!

You should receive e-mails from our system shortly ❤️

**Comment by jspark311** [comment]
@JamieSlome Checking back in on this. I never saw anything cross my inbox. Can you please either resend, or tell me what domain the email came from?

**Comment by JamieSlome** [comment]
@jspark311 - sorry that you didn't see anything come in. The e-mail would have been from ...@huntr.dev. Also, you can view one of the reports directly here:

https://huntr.dev/bounties/ba6de042-1235-42fe-8379-57b70d9c6c01/

**Comment by JamieSlome** [comment]
@jspark311 - it also looks like the e-mail in your `SECURITY.md` doesn't take the proper format of an e-mail as well.

**Comment by jspark311** [comment]
Please see the following issue:

https://github.com/jspark311/BuriedUnderTheNoiseFloor/issues/3
